# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  taskstrackertasksmanagerbackendapi:
    image: taskstrackertasksmanagerbackendapi
    build:
      context: .
      dockerfile: TasksTracker.TasksManager.Backend.Api/Dockerfile
    ports:
      - 5208:5208
