apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://taskstracker-state-store-jb.documents.azure.com:443/
  - name: masterKey
    value: "2Xa8b144IfF6oex8UZ0tWNvrWqsRVPfiMm1nCpLVs5heT7XYSnxqAhR78a0ZwzskAVFJ9F73Y22IACDbQhOtvw=="
  - name: database
    value: tasksmanagerdb
  - name: collection
    value: taskscollection
scopes:
- tasksmanager-backend-api